FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y install openssh-server
RUN apt-get -y install git
RUN apt-get -y install nano

# Setting openssh
RUN mkdir /var/run/sshd
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/sshd_config

# Adding git user
RUN adduser --system git
RUN mkdir -p /home/git/.ssh

# Clearing and setting authorized ssh keys
RUN echo '' > /home/git/.ssh/authorized_keys
RUN echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAr+hMbZaebyKmTblcfcmrMjBtsjbU1OqY/cXG+x9fQfv9jq8HXBBi0T1CYSntYq1Tf6TIRcn+So4xsZQ10NU6TxEp6biXikGb5DkD7fSTrPfiPXyRTLFBhfPYdbnETmh3q8yvmstrkc4KP0gqO6LEbM/Ywo9gc5Rl7cuaAW51T1k1bLsQXPfIQn6e6xJVzrYVpHz3/AIP/CMo3nF7WZBfyJGVW+pZfdfZMPbf4grWNlRg4wLKVRnBXaimJAo/PplPVGO0ZUEd6hr0fdVCQvr7C5U+LqsKP8Bf5zoXmb+TDbfZc9SmemWm8p9muKoGgYHoic/B+SQ6iAh25UIj+J5+tQ== rsa-key-20190822' >> /home/git/.ssh/authorized_keys
# RUN echo 'Second SSH public key' >> /home/git/.ssh/authorized_keys
# ...

# Updating shell to bash
RUN sed -i s#/home/git:/bin/false#/home/git:/bin/bash# /etc/passwd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]