FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y install openssh-server
RUN apt-get -y install git
RUN apt-get -y install nano
RUN apt-get -y install cron

# Setting openssh
RUN mkdir /var/run/sshd
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/sshd_config

# Adding git user
RUN adduser --system --shell /bin/bash git
RUN mkdir -p /home/git/.ssh

COPY office-ca.cer ./
RUN cat ./office-ca.cer >> /etc/ssl/certs/ca-certificates.crt

# Clearing and setting authorized ssh keys
RUN echo '' > /home/git/.ssh/authorized_keys
RUN echo 'First SSH public key' >> /home/git/.ssh/authorized_keys
# RUN echo 'Second SSH public key' >> /home/git/.ssh/authorized_keys
# ...

# Updating shell to bash
RUN sed -i s#/home/git:/bin/false#/home/git:/bin/bash# /etc/passwd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
