version: '3.3'
services:
  sftp:
      image: atmoz/sftp
      volumes:
          - /host/upload:/home/foo/upload
      ports:
          - "8080:22"
      expose:
          - '8080'
      command: foo:pass:1001