version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'picasso'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'nicolasr'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'qwerty12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'qwerty12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-56:/var/lib/mysql
# Names our volume
volumes:
  my-db-56: